### ISSUE TITLE
[Suggestion] Fix 55khz calculation

### ISSUE THREAD

**Issue by pedipanol** [takamichih/pmdwinbuild#1]
I'm not sure if it's a problem with PMDWin or with FMPMD itself, but whenever FMCalc55k is set on, it creates noise on higher FM frequencies, but disabling it makes aliasing noise-dependent instruments (such as Umemoto's hi-hats) not sound right.

On FMPMD itself it's not a big problem, because one can just set the sample rate on the ini to 55467hz and disable the FMCalc55k, then it'll sound alright, but it'll overwrite every time you change the settings on the application, and have syncronization problems with the display.

But even then, on other players based on PMDwin (such as [foo_input_fmpmd](https://ux.getuploader.com/foobar2000/download/31) ) you don't have this option at all. So I'd like to request for the FM calculation to be fixed, if possible...

But if it's not a problem with PMDWin.dll, I'll just delete this post, no problem.

Thanks for your work on pmdwinbuild!

**Comment by takamichih** [comment]
Hi Pedipanol, thanks for your insightful comment about this.

I also thought the sound was kinda glitchy but I didn't think it seriously and assumed it was Wine's fault, but you were right.
I took a quick look at opnaw.cpp and the linear interpolation algorithm had a dumb off-by-one error.
Now I think it is working correctly, but there still is considerable aliasing remaining because of limitations of the linear interpolator itself.
Maybe someday I should replace it with something better such as speexdsp resampler...

(Also thanks for checking this out even though manually building this is a PITA. Perhaps someday I will try to contact the original author about these patches.)

Attached files:
pmdwin.dll: fixed build
fmhigh_55467.wav: output of fixed pmdwin.dll, without resampling
fmhigh_44100_linearint_bug.wav: output of previous pmdwin.dll, with glitches
fmhigh_44100_linearint_aliasing.wav: output of fixed pmdwin.dll, with aliasing
[fmhigh.zip](https://github.com/takamichih/pmdwinbuild/files/3828173/fmhigh.zip)

**Comment by pedipanol** [comment]
It would be really cool to have a new interpolator, but for now this already fixes enough of the problem, thanks a lot!

**Comment by pedipanol** [comment]
Ah, I forgot to add one thing to the message, one way you could release this without licensing issues is by releasing it as a patch file such as .ips or .bps, like romhacks of old games do.

These files only store the difference between the original and modified version, so if you create a patch from a fixed build, one can just apply it to the original dll that can be downloaded from c60's website.

Attached is an example .bps file generated from the build you just sent me, you can apply it using [beat](https://www.romhacking.net/utilities/893/)

[pmdwinbuild.zip](https://github.com/takamichih/pmdwinbuild/files/3828216/pmdwinbuild.zip)

**Comment by takamichih** [comment]
Thanks, yeah I have no idea why I couldn't come up with the idea of binary patch, thank you so much for your suggestion.
I've uploaded under releases with additional bugfix (previous one actually didn't fix glitches when requested buffer length was longer than internal resampling buffer, didn't happen under FMPMD2000 but might occur on other players)
Also I had fun tinkering with winfmp.dll under Ghidra (but actually didn't when I found out that binary export functionality was not implemented yet...) and I patched the opcodes to fix the same resampling glitches.
